import {PDFDocument} from 'pdf-lib';
import samples from './samples.json' with {type:'json'};
import {assert,audit,digest,emailValid,makeEnvelope,transition,uid,now,verifyAudit} from '../public/js/core.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const clean=d=>{const result=structuredClone(d);result.recipients.forEach(r=>delete r.tokenHash);return result;};
export function createService(env){
const db=()=>{assert(env.DB,'Document storage is temporarily unavailable.',503);return env.DB;};
const first=(sql,...v)=>db().prepare(sql).bind(...v).first();
const all=async(sql,...v)=>(await db().prepare(sql).bind(...v).all()).results;
const run=(sql,...v)=>db().prepare(sql).bind(...v).run();
async function access(id,user){const row=await first('SELECT * FROM envelopes WHERE id=?',id);assert(row,'Agreement not found.',404);const d=JSON.parse(row.data);let permission=d.owner===user.id?'owner':(await first('SELECT role FROM members WHERE envelope=? AND email=?',id,user.email))?.role;if(!permission&&d.kind==='agreement'&&d.status!=='draft'&&d.recipients.some(r=>r.email.toLowerCase()===user.email))permission='recipient';assert(permission,'You do not have access to this agreement.',403);return {d,permission};}
async function saveNew(d){await run('INSERT INTO envelopes (id,owner,title,status,revision,data,updated) VALUES (?,?,?,?,?,?,?)',d.id,d.owner,d.title,d.status,d.revision,JSON.stringify(d),d.updated);return d;}
async function checkDocs(documents,user,current=[]){assert(Array.isArray(documents)&&documents.length<=20,'Invalid documents.');const result=[];for(const document of documents){if(document.builtin){assert(['consulting','nda','offer'].includes(document.builtin),'Invalid sample document.');result.push({id:current.find(x=>x.builtin===document.builtin&&x.id===document.id)?.id||'builtin:'+uid(),builtin:document.builtin,name:document.name||'Sample agreement.pdf',pages:[{width:612,height:792}],digest:samples[document.builtin]});continue;}const file=await first('SELECT * FROM files WHERE id=?',document.id);assert(file&&(file.owner===user.id||current.some(x=>!x.builtin&&x.id===file.id)),'Document unavailable.',403);result.push({id:file.id,name:file.name,pages:JSON.parse(file.pages),digest:file.digest,size:file.size});}return result;}
async function commit(before,after){const result=await run('UPDATE envelopes SET title=?,status=?,revision=?,data=?,updated=? WHERE id=? AND revision=?',after.title,after.status,after.revision,JSON.stringify(after),after.updated,after.id,before.revision);assert(result.meta.changes===1,'A collaborator just updated this agreement. Reload the latest version before saving.',409);return after;}
return async function handle(request){try{const url=new URL(request.url);const path=url.pathname.replace(/^\/api\/?/,'').split('/');const id=request.headers.get('oai-authenticated-user-id');const email=request.headers.get('oai-authenticated-user-email')?.toLowerCase();assert(id&&email,'Sign in to open your workspace.',401);let name=email;try{name=decodeURIComponent(request.headers.get('oai-authenticated-user-full-name')||email);}catch{}const user={id,email,name};const method=request.method;
if(method!=='GET'){assert(request.headers.get('origin')===url.origin||!request.headers.get('origin'),'Cross-origin request rejected.',403);assert(request.headers.get('sec-fetch-site')!=='cross-site','Cross-origin request rejected.',403);assert(Number(request.headers.get('content-length')||0)<11*1024*1024,'Upload exceeds 10 MB.',413);}
const body=async()=>{const text=await request.text();assert(text.length<=2000000,'Request too large.',413);try{return JSON.parse(text||'{}');}catch{assert(false,'Invalid JSON.');}};
if(path[0]==='bootstrap'&&method==='GET'){const rows=await all('SELECT DISTINCT e.* FROM envelopes e LEFT JOIN members m ON e.id=m.envelope WHERE e.owner=? OR m.email=? OR (e.status!=\'draft\' AND json_extract(e.data,\'$.kind\')=\'agreement\' AND EXISTS (SELECT 1 FROM json_each(e.data,\'$.recipients\') r WHERE lower(json_extract(r.value,\'$.email\'))=?)) ORDER BY e.updated DESC',user.id,user.email,user.email);const profile=await first('SELECT data FROM profiles WHERE id=?',user.id);return json({user,profile:profile?JSON.parse(profile.data):{},envelopes:rows.map(x=>{const d=clean(JSON.parse(x.data));delete d.values;delete d.audit;return d;})});}
if(path[0]==='profile'&&method==='POST'){const p=await body();const safe={name:String(p.name||user.name).slice(0,150),company:String(p.company||'').slice(0,150),signature:String(p.signature||'').slice(0,150)};await run('INSERT INTO profiles(id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data',user.id,JSON.stringify(safe));return json(safe);}
if(path[0]==='seed'&&method==='POST'){const exists=await first('SELECT id FROM envelopes WHERE owner=? LIMIT 1',user.id);assert(!exists,'Sample agreements are only available in an empty workspace.',409);const examples=[['Website redesign agreement','consulting','sent','Avery Morgan','avery@example.com'],['Mutual non-disclosure agreement','nda','draft','Jordan Lee','jordan@example.com'],['Employment offer · Product designer','offer','draft','Taylor Chen','taylor@example.com'],['Consulting services agreement','consulting','sent',user.name,user.email]];for(const [title,builtin,status,rname,remail] of examples){const doc={id:uid(),builtin,name:title+'.pdf',pages:[{width:612,height:792}],digest:samples[builtin]};const rec={id:uid(),name:rname,email:remail,role:'signer',order:1,status:'pending'};const d=makeEnvelope({title,owner:user.id,ownerEmail:user.email,documents:[doc],recipients:[rec],demo:true});d.fields=[{id:uid(),type:'signature',recipient:rec.id,document:doc.id,page:0,x:.12,y:.765,w:.3,h:.05,required:true},{id:uid(),type:'date',recipient:rec.id,document:doc.id,page:0,x:.6,y:.765,w:.22,h:.04,required:true}];d.status=status;await audit(d,user.email,'Created','Sample agreement for exploring Velsign');await saveNew(d);}return json({ok:true});}
if(path[0]==='files'&&method==='POST'){assert(env.BUCKET,'File storage unavailable.',503);const bytes=new Uint8Array(await request.arrayBuffer());assert(bytes.length<=10*1024*1024&&bytes.length>=8,'PDF must be under 10 MB.',413);assert(new TextDecoder().decode(bytes.slice(0,5))==='%PDF-','Upload a PDF document.');let pdf;try{pdf=await PDFDocument.load(bytes,{updateMetadata:false});}catch{assert(false,'This PDF is encrypted or cannot be opened.');}assert(pdf.getPageCount()<=100,'Each PDF can contain up to 100 pages.');assert(pdf.getPages().every(p=>p.getRotation().angle%360===0),'Rotate PDF pages to 0° before uploading.');assert(pdf.getPages().every(p=>{const c=p.getCropBox(),m=p.getMediaBox();return m.x===0&&m.y===0&&c.x===0&&c.y===0&&Math.abs(c.width-m.width)<.01&&Math.abs(c.height-m.height)<.01;}),'Flatten or normalize cropped PDF pages before uploading.');assert(pdf.getForm().getFields().length===0,'Flatten existing PDF form fields before uploading.');const fid=uid();const fname=(decodeURIComponent(request.headers.get('x-filename')||'Document.pdf')).slice(0,200);const pages=pdf.getPages().map(p=>({width:p.getWidth(),height:p.getHeight()}));const hash=await digest(bytes);await env.BUCKET.put(fid,bytes,{httpMetadata:{contentType:'application/pdf'}});try{await run('INSERT INTO files(id,owner,name,digest,pages,size) VALUES(?,?,?,?,?,?)',fid,user.id,fname,hash,JSON.stringify(pages),bytes.length);}catch(e){await env.BUCKET.delete(fid);throw e;}return json({id:fid,name:fname,digest:hash,pages,size:bytes.length});}
if(path[0]==='files'&&path[1]&&method==='GET'){const f=await first('SELECT * FROM files WHERE id=?',path[1]);assert(f,'File not found.',404);if(f.owner!==user.id){const {d}=await access(url.searchParams.get('envelope'),user);assert(d.documents.some(x=>!x.builtin&&x.id===f.id),'Access denied.',403);}const object=await env.BUCKET.get(f.id);assert(object,'File unavailable.',404);return new Response(object.body,{headers:{'Content-Type':'application/pdf','Content-Disposition':`inline; filename*=UTF-8''${encodeURIComponent(f.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
if(path[0]==='envelopes'&&!path[1]&&method==='POST'){const b=await body();const documents=await checkDocs(b.documents||[],user);const d=makeEnvelope({title:String(b.title||'Untitled agreement').slice(0,200),owner:user.id,ownerEmail:user.email,documents,kind:b.kind==='template'?'template':'agreement'});await audit(d,user.email,'Created');await saveNew(d);return json(clean(d),201);}
if(path[0]==='envelopes'&&path[1]){const {d,permission}=await access(path[1],user);const actor={...user,permission};const action=path[2];
if(!action&&method==='GET')return json({...clean(d),permission});
if(action==='action'&&method==='POST'){const b=await body();assert(b.revision===d.revision,'The agreement changed. Reload before saving.',409);if(b.action==='edit'&&b.payload?.documents)b.payload.documents=await checkDocs(b.payload.documents,user,d.documents);if(b.action==='sign'){for(const value of Object.values(b.payload?.values||{})){if(typeof value==='string'&&value.startsWith('data:image/png;base64,')){try{assert(/^data:image\/png;base64,[A-Za-z0-9+/]+={0,2}$/.test(value),'Invalid signature image.');const probe=await PDFDocument.create();const image=await probe.embedPng(value);assert(image.width<=4096&&image.height<=4096,'Signature image too large.');}catch{assert(false,'Signature image is invalid. Please draw or type it again.');}}}}const after=await transition(d,b.action,b.payload||{},actor);await commit(d,after);return json({...clean(after),permission});}
if(action==='duplicate'&&method==='POST'){assert(['owner','editor'].includes(permission),'Editing access required.',403);const b=await body();const copy=makeEnvelope({title:(b.title||d.title+(b.kind==='template'?' template':' (copy)')).slice(0,200),owner:user.id,ownerEmail:user.email,documents:[],kind:b.kind==='template'?'template':'agreement',demo:false});for(const doc of d.documents){if(doc.builtin){copy.documents.push(doc);continue;}const file=await first('SELECT * FROM files WHERE id=?',doc.id);assert(file,'Source document unavailable.',404);const bytes=await env.BUCKET.get(doc.id);assert(bytes,'Source document unavailable.',404);const newid=uid();await env.BUCKET.put(newid,bytes.body,{httpMetadata:{contentType:'application/pdf'}});await run('INSERT INTO files(id,owner,name,digest,pages,size) VALUES(?,?,?,?,?,?)',newid,user.id,file.name,file.digest,file.pages,file.size);copy.documents.push({...doc,id:newid});}copy.recipients=d.recipients.map(({tokenHash,status,signedAt,signedBy,...r})=>r);copy.fields=d.fields.map(f=>({...f,document:copy.documents[d.documents.findIndex(x=>x.id===f.document)].id}));copy.message=d.message;copy.sequential=d.sequential;await audit(copy,user.email,'Created',`Copied from ${d.id}`);await saveNew(copy);return json({...clean(copy),permission:'owner'},201);}
if(action==='links'&&method==='POST'){assert(permission==='owner','Owner access required.',403);const b=await body();const token=uid().replaceAll('-','')+uid().replaceAll('-','');const after=await transition(d,'link',{recipient:b.recipient,tokenHash:await digest(token)},actor);await commit(d,after);return json({url:`${url.origin}/#sign/${d.id}/${b.recipient}/${token}`,envelope:{...clean(after),permission}});}
if(action==='audit'&&method==='GET')return json({envelope:d.id,valid:await verifyAudit(d.audit),events:d.audit,documents:d.documents.map(x=>({name:x.name,sha256:x.digest})),qualification:'Internal SHA-256 hash chain; no external timestamp or PKI certificate.'});
if(action==='members'){assert(['owner','editor'].includes(permission),'Editing access required.',403);if(method==='GET')return json(await all('SELECT id,email,role FROM members WHERE envelope=?',d.id));assert(permission==='owner','Owner access required.',403);const b=await body();assert(emailValid(b.email),'Enter a valid email.');if(method==='DELETE')await run('DELETE FROM members WHERE envelope=? AND email=?',d.id,b.email.toLowerCase());else{assert(['editor','viewer'].includes(b.role),'Choose editor or viewer.');await run('INSERT INTO members(id,envelope,email,role) VALUES(?,?,?,?) ON CONFLICT(envelope,email) DO UPDATE SET role=excluded.role',uid(),d.id,b.email.toLowerCase(),b.role);}return json({ok:true});}
if(action==='comments'){assert(permission!=='recipient','Workspace access required.',403);if(method==='GET')return json(await all('SELECT * FROM comments WHERE envelope=? ORDER BY created',d.id));const b=await body();assert(permission!=='viewer','Comment access required.',403);if(method==='PATCH'){await run('UPDATE comments SET resolved=? WHERE id=? AND envelope=?',b.resolved?1:0,b.id,d.id);return json({ok:true});}assert(b.body?.trim()&&b.body.length<=4000,'Comment must be between 1 and 4,000 characters.');const c={id:uid(),envelope:d.id,author:user.id,name:user.name,body:b.body,created:now(),resolved:0};await run('INSERT INTO comments(id,envelope,author,name,body,created,resolved) VALUES(?,?,?,?,?,?,0)',c.id,d.id,c.author,c.name,c.body,c.created);return json(c,201);}
if(action==='presence'){if(method==='POST')await run('INSERT INTO presence(id,envelope,name,seen) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,seen=excluded.seen',d.id+':'+user.id,d.id,user.name,Date.now());return json({revision:d.revision,people:await all('SELECT name,seen FROM presence WHERE envelope=? AND seen>?',d.id,Date.now()-16000)});}}
if(path[0]==='sign'&&method==='GET'){const {d,permission}=await access(path[1],user);const r=d.recipients.find(x=>x.id===path[2]);assert(r,'Recipient not found.',404);assert(r.email.toLowerCase()===user.email,'Sign in with the recipient email.',403);if(url.searchParams.get('token'))assert(await digest(url.searchParams.get('token'))===r.tokenHash,'Signing link is invalid or was replaced.',403);return json({...clean(d),permission,signingRecipient:r.id});}
if(path[0]==='contacts'){if(method==='GET')return json(await all('SELECT * FROM contacts WHERE owner=? ORDER BY name',user.id));const b=await body();if(method==='DELETE'){await run('DELETE FROM contacts WHERE id=? AND owner=?',b.id,user.id);return json({ok:true});}assert(emailValid(b.email)&&b.name?.trim()&&b.name.length<150,'Provide a name and valid email.');const c={id:uid(),name:b.name,email:b.email.toLowerCase(),company:String(b.company||'').slice(0,150)};await run('INSERT INTO contacts(id,owner,name,email,company) VALUES(?,?,?,?,?)',c.id,user.id,c.name,c.email,c.company);return json(c,201);}
return json({error:'Route not found.'},404);
}catch(error){if(!error.status)console.error('Velsign request failed',error);return json({error:error.status?error.message:'Unable to save right now. Your changes have been kept on this screen. Try again.'},error.status||503);}};
}
